---
- hosts: webserv
  become: true
  tasks:
    - name: install epel      
      yum: name=epel-release

    - name: install web component
      yum: name="{{ packages }}" state=present update_cache=yes enablerepo=epel
      vars:
        packages: 
          - httpd
          - mod_wsgi
          - python-pip
          - python-virtualenv

    - name: ensure httpd is running     
      service:       
        name: httpd       
        state: started

    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: yes
        state: enabled
      notify: restart the firewall changes

    - name: ensure mod_wsgi enabled
      apache2_module: state=present name=wsgi
      notify: restart apache2

    - name: copy app to the source
      copy: src=demo/app/ dest=/var/www/demo mode=0755
      notify: restart apache2
    
    - name: copy apache config file
      copy: src=demo/demo.conf dest=/etc/httpd/conf.d/demo.conf mode=0755
      notify: restart apache2

    - name: setup pip env
      pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv virtualenv_python=python3.5
      notify: restart apache2

 
  handlers:
    - name: restart apache2
      service: name=httpd state=restarted
    - name: restart the firewall changes       
      service:         
        name: firewalld         
        state: restarted
