---
    - name: Install mysql-server
      yum: name="{{ item }}" state=present update_cache=yes
      with_items:
         - https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
         - mysql-server
         - MySQL-python

    - name: Ensure mysql running
      service: name=mysqld state=started enabled=yes

    - name: Ensure mysql listening on all port
      lineinfile: dest=/etc/my.cnf regexp=^bind-address line="bind-address=0.0.0.0"
      notify: restart mysql

    - name: Create a database
      mysql_db: name=demo state=present

    - name: Create user in mysql
      mysql_user: name=demo password=S@nj@y1234 priv=demo.*:ALL host='%' state=present
