---
    - name: Install mysql-server
      yum: name="{{ item }}" state=present update_cache=yes
      with_items:
         - https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
         - mysql-server
         - MySQL-python

    - name: Ensure mysql running
      service: name=mysqld state=started enabled=yes

    - name: Ensure mysql listening on all port
      lineinfile: dest=/etc/my.cnf regexp=^bind-address line="bind-address={{ ansible_default_ipv4.address }}"
      notify: restart mysql

    - name: Create a database
      mysql_db: name="{{ db_name }}" state=present

    - name: Create user in mysql
      mysql_user: name="{{ db_username }}" password="{{ db_password }}" priv={{ db_username }}.*:ALL host='{{ db_host }}' state=present
