---
   - name: install epel
     yum: name=epel-release

   - name: install tools
     yum: name="{{ item }}" state=present      
     with_items:
       - python-httplib2

   - name: install nginx
     yum:
       name: nginx
       enablerepo: "epel"
       state: present
       update_cache: yes


   - name: remove default nginex conf
     file: path=/etc/nginx/nginx.conf state=absent
  
   - name: create nginx config file and put this in site-available
     template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644
     with_dict: "{{ sites }}"
     notify: restart nginx

   - name: ansure nginx service started
     service: name=nginx state=started enabled=yes

